### ISSUE TITLE
Height of XSLT-based examples

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/xstuff#18]
@charlietaylor98 When I look at the embedded SVG in the generated paper (_Bal2021birn0505.html_), there seems to be too much space below the images, which I think is because of the way the `@height` and `@width` are specified on the `<svg>` element. When I look at _vert-relative.xsl_, it looks as if you set an explicit `@height` by adding 300 to the computed `$max_height`. (There's also extra width, but that's less important, since it doesn't affect the layout of adjacent components.)

Is there a way to avoid using the 300, such as by replacing it with a computed value, or, if not, a smaller fixed value? Not only is it a magic number (that is, hard-coded and with no self-documenting explanation of why the value is what it is), which we're trying to avoid, but it's also larger than I think we want it to be.

**Comment by charlietaylor98** [comment]
@djbpitt I can replace `@height` in those examples with a computed value, similar to what I'm doing to fix `@translate` in the JavaScript examples

**Comment by djbpitt** [comment]
@charlietaylor98 The height of the horizontal graph looks good, but the vertical and diagonal ones, when viewed inside the HTML file, show large gaps at the bottom. When I open the SVG file itself, the culprit seems to be the `@height` value on the `<svg>` element. Is it possible that there's something amiss in the way you computed that value? That the horizontal one looks correct but the vertical and diagonal ones don't suggests that there may be something afoot in the way the space occupied by the bar labels is computed.

**Comment by charlietaylor98** [comment]
@djbpitt Ah, looks like my computed `@height` was way off -- I added had added an extra value that made it a lot taller than it needed to be! I just fixed it and pushed the change, let me know what you think

**Comment by djbpitt** [comment]
@charlietaylor98 Looks much better! Thank you for the quick fix!
